albergue/urls.py
from django.conf.urls import url, include
from django.conf.urls import handler403, handler404, handler500
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.views import LoginView 
from . import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    #logs
    url(r'^login/', LoginView.as_view(template_name= 'login/index.html'), name='login'),
    url(r'^logout/', views.logout_view,name='logout'),
    #sistemas
    url(r'^panel/', login_required(views.panel.as_view(), login_url='login'), name='panel'),
    url(r'^almacen/',include('almacen.urls')),
    url(r'^',include('base.urls')),
    #indexform/test
    url(r'^form/', login_required(views.formindex, login_url='/'), name='form'),
    #perfil url
    url(r'^perfil/$', login_required(views.perfilView, login_url='/'), name="perfil"),
    #calendario/test
    url(r'^swingtime/events/type/([^/]+)/$', views.event_type, name='calen-event'),
    url(r'^swingtime/', include('swingtime.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Solo para produccion
handler403 = views.status_403
handler404 = views.status_404
handler500 = views.status_500

almacen/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name='almacen'

urlpatterns = [
        #almacen normal
        url(r'^$', login_required(views.index, login_url='/'), name="index"),
        url(r'^medicamentos/$', login_required(views.med, login_url='/'), name="medicamentos"),
        #Creat,Delete,add-1,minus-1
        url(r'^productos/create$', login_required(views.ProductosCreate.as_view(), login_url='/'), name="add-producto"),
        url(r'^medicamentos/create$', login_required(views.MedicamentosCreate.as_view(), login_url='/'), name="add-medicamento"),
        url(r'^addp/(?P<producto_id>[0-9]+)$', login_required(views.add_producto, login_url='/'), name="add-1"),
        url(r'^minusp/(?P<producto_id>[0-9]+)$', login_required(views.minus_producto, login_url='/'), name="minus-1"),
        url(r'^addm/(?P<medicamento_id>[0-9]+)$', login_required(views.add_medicamento, login_url='/'), name="addm-1"),
        url(r'^minusm/(?P<medicamento_id>[0-9]+)$', login_required(views.minus_medicamento, login_url='/'), name="minusm-1"),
 
        #insumos
        url(r'^insumos/$', login_required(views.insumos, login_url='/'), name="insumos"),
        #Reportes de diferentes cosas.
        url(r'^reporte/producto$',  login_required(views.PDFProductos.as_view(), login_url='/'), name="pro"),
        url(r'^reporte/medicamento$',  login_required(views.PDFMedicamentos.as_view(), login_url='/'), name="med"),
        url(r'^reporte/producto/caducado$',  login_required(views.PDFProductosC.as_view(), login_url='/'), name="pc"),
        url(r'^reporte/medicamento/caducado$',  login_required(views.PDFMedicamentosC.as_view(), login_url='/'), name="mc"),
        url(r'^reporte/insumos/prestados$',  login_required(views.PDFInsumosP.as_view(), login_url='/'), name="ip"),

        #Reportes de diferentes cosas Excel.
        url(r'^reporte/producto/xls$',  login_required(views.XLSProductos.as_view(), login_url='/'), name="proxls"),
        url(r'^reporte/medicamento/xls$',  login_required(views.XLSMedicamentos.as_view(), login_url='/'), name="medxls"),
        url(r'^reporte/producto/caducado/xls$',  login_required(views.XLSProductosC.as_view(), login_url='/'), name="pcxls"),
        url(r'^reporte/medicamento/caducado/xls$',  login_required(views.XLSMedicamentosC.as_view(), login_url='/'), name="mcxls"),
        url(r'^reporte/insumos/prestados/xls$',  login_required(views.XLSInsumosP.as_view(), login_url='/'), name="ipxls")
    ]

base/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name='base'

urlpatterns = [
        # API URLS
        url(r'^municipios/(?P<pk>[0-9]+)$',views.MunicipioList.as_view()),
        #normalVistas
        url(r'^camas$', login_required(views.index, login_url='/'), name="index"),
        url(r'^pacientes$', login_required(views.pacienteView, login_url='/'), name="pacientes"),
        url(r'^personal$', login_required(views.personalView, login_url='/'), name="personal"),
        url(r'^personal/(?P<pk>[0-9]+)/$', login_required(views.PersonalDetail.as_view(), login_url='/'), name="personal-detail"),
        url(r'^paciente/(?P<pk>[0-9]+)/$', login_required(views.PacienteDetail.as_view(), login_url='/'), name="paciente-detail"),
        url(r'^Ingresados/$', login_required(views.IngresadosView, login_url='/'), name="ingresados"),
        url(r'^Ingresado/(?P<pk>[0-9]+)/$', login_required(views.IngresadosDetail.as_view(), login_url='/'), name="ingre-detail"),

        #forms
        url(r'^registro/pacientes$', login_required(views.addPacientes, login_url='/'), name="add-pacientes"),
        url(r'^registro/ingreso$', login_required(views.IngresoCreate, login_url='/'), name="add-ingreso"),
        url(r'^registro/acompa/(?P<ingreso_id>[0-9]+)$', login_required(views.addAcompa, login_url='/'), name="add-acompa"),
        url(r'^ingreso/form$', login_required(views.ingresoForm, login_url='/'), name="ingreso-form"),
        url(r'^ingreso/acompa$', login_required(views.addAcompaForm, login_url='/'), name="add-acompaform"),
        url(r'^reporte/(?P<interno_id>[0-9]+)$', login_required(views.add_reporte, login_url='/'), name="add-reporte"),
        url(r'^insuform/(?P<ingreso_id>[0-9]+)$', login_required(views.add_insumos, login_url='/'), name="add-insumos"),

        # delete forms 
        url(r'^eliminar/pacientes$', login_required(views.IngresoDrop, login_url='/'), name="drop-ingreso"),
        url(r'^eliminar/pacientes/paso2$', login_required(views.IngresoDrop2, login_url='/'), name="drop-ingreso2"),
        url(r'^eliminar/pacientes/(?P<ingreso_id>[0-9]+)$', login_required(views.IngresoDrop22, login_url='/'),name="drop-ingreso22"),
        url(r'^eliminar/pacientes/paso3$', login_required(views.IngresoDrop3, login_url='/'), name="drop-ingreso3"),

        #reportes variados
        url(r'^reporte/camas$',  login_required(views.PDFCamas.as_view(), login_url='/'), name="camaspdf"),
        url(r'^reporte/comidas$',  login_required(views.PDFComidas.as_view(), login_url='/'), name="comidaspdf"),
        url(r'^reporte/reportes$',  login_required(views.PDFReportes.as_view(), login_url='/'), name="reportespdf"),

        #reportes variados excel
        url(r'^reporte/camas/xls$',  login_required(views.XLSCamas.as_view(), login_url='/'), name="camasxls"),
        url(r'^reporte/comidas/xls$',  login_required(views.XLSComidas.as_view(), login_url='/'), name="comidasxls"),
        url(r'^reporte/reportes/xls$',  login_required(views.XLSReportes.as_view(), login_url='/'), name="reportesxls"),

        #Ayuda
        url(r'^ayuda$',  login_required(views.ayuda, login_url='/'), name="ayuda"),
    ]

almacen/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.conf import settings
from django.http import HttpResponse

from easy_pdf.views import PDFTemplateView
from openpyxl import Workbook

from .models import Productos, Medicamentos, Insumos
from base.models import Profile,InsumosPrestados,Ingreso



#utils
import datetime

# Create your views here.

def index(request):
    #check your type of user.
    profiles = Profile.objects.get(user=request.user)
    if not profiles.user_type > 3 and profiles.user_type < 8:
        return redirect('/')

    pro = Productos.objects.all()
    #dinamycs dates
    start_date = datetime.date.today()
    end_date = start_date + datetime.timedelta(days=10)
    #search of the close dates
    pros = Productos.objects.filter(fechaC__range=(start_date, end_date))
    if pros != None:
        message = "Existen Productos a punto de caducar"
    else:
        message = "Que oso que seas almacenista"

    return render(request, 'almacen/index.html', {
        'message':message,
        'productos': pro,
        'prod':pros,
        'user': profiles
    })

def med(request):
    #check your type of user.
    profiles = Profile.objects.get(user=request.user)
    if not profiles.user_type > 3 and profiles.user_type < 8:
        return redirect('/')

    medi = Medicamentos.objects.all()
    #dinamycs dates
    start_date = datetime.date.today()
    end_date = start_date + datetime.timedelta(days=10)
    #search of the close dates
    medis = Medicamentos.objects.filter(fechaC__range=(start_date, end_date))
    if medis != None:
        message = "Existen Medicamentos a punto de caducar"
    else:
        message = "Que oso que seas almacenista"

    return render(request, 'almacen/med.html', {
        'message':message,
        'medicamentos': medi,
        'medc': medis,
        'user': profiles
    })

def insumos(request):
    #check your type of user.
    profiles = Profile.objects.get(user=request.user)
    if not profiles.user_type > 3 and profiles.user_type < 8:
        return redirect('/')

    insu = Insumos.objects.filter(especial=False)

    #insumos espaciales
    especiales = Insumos.objects.filter(especial=True)
    if especiales == None:
        message = "Existe un problema no hay insumos especiales"
    else:
        message = "Que oso que seas almacenista de insumos"

    return render(request, 'almacen/insumos.html', {
        'message':message,
        'insumos': insu,
        'espe': especiales,
        'user': profiles
    })

# vistas CREATE,DELETE,add-1,minus-1
class ProductosCreate(generic.CreateView):

    model = Productos
    success_url = '/almacen'
    fields = ['name','cantidad','refrigerado','fechaC','almacen','especial']
 
class MedicamentosCreate(generic.CreateView):

    model = Medicamentos
    success_url = '/almacen/medicamentos'
    fields = ['name','cantidad','refrigerado','fechaC']

def add_producto(request, producto_id):
    produ = Productos.objects.get(id=producto_id)
    produ.cantidad += 1
    produ.save()
    return redirect('almacen:index')

def minus_producto(request, producto_id):
    produ = Productos.objects.get(id=producto_id)
    produ.cantidad -= 1
    produ.save()
    return redirect('almacen:index')


def add_medicamento(request, medicamento_id):
    medi = Medicamentos.objects.get(id=medicamento_id)
    medi.cantidad += 1
    medi.save()
    return redirect('almacen:medicamentos')

def minus_medicamento(request, medicamento_id):
    medi = Medicamentos.objects.get(id=medicamento_id)
    medi.cantidad -= 1
    medi.save()
    return redirect('almacen:medicamentos')


#Reportes del almacen
class PDFProductosC(PDFTemplateView):
    template_name = 'almacen/test.html'

    base_url ='file://' + settings.STATIC_ROOT
    download_filename = 'Productos_a_caducar.pdf'

    def get_context_data(self, **kwargs):
        #dinamycs dates
        
        start_date = datetime.date.today()
        past = start_date -datetime.timedelta(days=31)
        end_date = start_date + datetime.timedelta(days=10)
        #search of the close dates
        pros = Productos.objects.filter(fechaC__range=(start_date, end_date))
        cad = Productos.objects.filter(fechaC__range=(past, start_date))
        return super(PDFProductosC, self).get_context_data(
                    pagesize='A4',
                    title='Productos a caducar',
                    prod=pros,
                    cadu=cad,
                    **kwargs
                )


class PDFMedicamentosC(PDFTemplateView):
    template_name = 'almacen/testm.html'

    base_url ='file://' + settings.STATIC_ROOT
    download_filename = 'Medicamentos_a_caducar.pdf'

    def get_context_data(self, **kwargs):
        #dinamycs dates
        start_date = datetime.date.today()
        past = start_date -datetime.timedelta(days=31)
        end_date = start_date + datetime.timedelta(days=10)
        #search of the close dates
        med = Medicamentos.objects.filter(fechaC__range=(start_date, end_date))
        cad = Medicamentos.objects.filter(fechaC__range=(past, start_date))
        return super(PDFMedicamentosC, self).get_context_data(
                    pagesize='A4',
                    title='Medicamentos a caducar',
                    medc=med,
                    cadu=cad,
                    **kwargs
                )


class PDFInsumosP(PDFTemplateView):
    template_name = 'almacen/testi.html'

    base_url ='file://' + settings.STATIC_ROOT
    download_filename = 'Insumos_prestados.pdf'

    def get_context_data(self, **kwargs):
       #search of the close dates
        insu = InsumosPrestados.objects.all()
        return super(PDFInsumosP, self).get_context_data(
                    pagesize='A4',
                    title='Insumos prestados',
                    insup=insu,
                    **kwargs
                )



class PDFProductos(PDFTemplateView):
    template_name = 'almacen/productospdf.html'

    base_url ='file://' + settings.STATIC_ROOT
    download_filename = 'Productos.pdf'

    def get_context_data(self, **kwargs):
        pros = Productos.objects.all()
        return super(PDFProductos, self).get_context_data(
                    pagesize='A4',
                    title='Productos',
                    prod=pros,
                    **kwargs
                )


class PDFMedicamentos(PDFTemplateView):
    template_name = 'almacen/medicamentospdf.html'

    base_url ='file://' + settings.STATIC_ROOT
    download_filename = 'Productos.pdf'

    def get_context_data(self, **kwargs):
        med = Medicamentos.objects.all()
        return super(PDFMedicamentos, self).get_context_data(
                    pagesize='A4',
                    title='Medicamentos',
                    medicamentos=med,
                    **kwargs
                )



#Reportes del almacen XLS
class XLSProductos(generic.TemplateView):
    def get(self,request,*args,**kwargs):
        pros = Productos.objects.all()
        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'REPORTE DE PRODUCTOS'

        ws.merge_cells('B1:E1')
        ws['B3']='NOMBRE'
        ws['C3']='CANTIDAD'
        ws['D3']='REFRIGERADO'
        ws['E3']='ALMACEN'
        ws['F3']='FECHA CADUCIDAD'

        cont = 5
        for p in pros:
            ws.cell(row= cont,column=2).value = p.name
            ws.cell(row= cont,column=3).value = p.cantidad
            if p.refrigerado == True:
                ws.cell(row= cont,column=4).value = 'Si'
            else:
                ws.cell(row= cont,column=4).value = 'No'
            ws.cell(row= cont,column=5).value = p.almacen
            ws.cell(row= cont,column=6).value = p.fechaC
            cont+=1
        nombre_archivo = "ReporteProductos.xlsx"
        response = HttpResponse(content_type="application/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response




class XLSMedicamentos(generic.TemplateView):
    def get(self,request,*args,**kwargs):
        pros = Medicamentos.objects.all()
        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'REPORTE DE Medicamentos'

        ws.merge_cells('B1:E1')
        ws['B3']='NOMBRE'
        ws['C3']='CANTIDAD'
        ws['D3']='REFRIGERADO'
        ws['E3']='FECHA CADUCIDAD'

        cont = 4
        for p in pros:
            ws.cell(row= cont,column=2).value = p.name
            ws.cell(row= cont,column=3).value = p.cantidad
            if p.refrigerado == True:
                ws.cell(row= cont,column=4).value = 'Si'
            else:
                ws.cell(row= cont,column=4).value = 'No'
            ws.cell(row= cont,column=5).value = p.fechaC
            cont+=1

        nombre_archivo = "ReporteMedicamentos.xlsx"
        response = HttpResponse(content_type="application/ms-excel")
        content = "attachment; filename = {0}".format(nombre_archivo)
        response['Content-Disposition'] = content
        wb.save(response)
        return response


class XLSProductosC(generic.TemplateView):
    def get(self,request,*args,**kwargs):
        start_date = datetime.date.today()
        past = start_date -datetime.timedelta(days=31)
        #search of the close dates
        cad = Productos.objects.filter(fechaC__range=(past, start_date))

        wb = Workbook()
        ws = wb.active
        ws['B1'] = 'REPORTE DE PRODUCTOS CADUCADOS'

        ws.merge_cells('B1:E1')
        ws['B3']='NOMBRE'
        ws['C3']='CANTIDAD'
        ws['D3']='FECHA CADUCIDAD'

        cont = 3
        for p in cad:
            ws.cell(row= cont,column=2).value = p.name
            ws.cell(row= cont,column=3).value = p.cantidad
            ws.cell(row= cont,column=4).value = p.fechaC
            cont+=1

templates/almacen/alert.html
{% if message != '' %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Ups!</strong> {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endif %}

templates/almacen/index.html
{% extends '../base.html' %}
{% block title %}Almacen | DIF Jalisco{% endblock %}
{% load static %}

{% block content %}
{% include "almacen/navbar.html" %}

{# Cambiar todo esto para que sea dinamico #}
<div class="container-fluid">
    <div class="row">
        <main role="main">
            <div class="flex-wrap flex-md-nowrap pt-3 pb-2 mb-3 border-bottom">
                <div class="row">
                    <div class="col-md-1 col-auto"> <i class="fas fa-box-open fa-3x"></i> </div>
                    <div class="col-md-1 col-auto">
                    <h1>Productos</h1>
                </div>
            </div>
            </div>
	{% include "almacen/sidebar.html" %}

{% if prod != None %}
</table>
{% include "almacen/alert.html" %}
<div class="table-responsive">
<table class="table table-hover table-danger">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cantidad</th>
      <th>Caducidad</th>
    </tr>
  </thead>
  <tbody>
  {% for p in prod %}
 <tr>
	 <td>{{p.name}}</td>
	 <td>{{p.cantidad}}</td>
	 <td>{{p.fechaC}}</td>
  </tr>
  {% endfor %}
</tbody>
</table>
</div>
<br>
<br>
{%endif%}

<div class="table-responsive">
<table class = "table table-hover">
    <thead>
  <tr>
    <th>Nombre</th>
    <th>Cantidad</th>
    <th>Caducidad</th>
	{%if user.user_type != 5 %}
    <th>Acciones</th>
	{%endif%}
  </tr>
  </thead>
   <tbody id="myTable">
  {% for pro in productos %}
 <tr>
	 <td>{{pro.name}}</td>
	 <td>{{pro.cantidad}}</td>
	 <td>{{pro.fechaC}}</td>
	{%if user.user_type != 5%}
	<td>                
	<form action="{% url 'almacen:add-1' pro.id %}" method="post" style="display: inline;">
		{% csrf_token %}
		<button type="submit" class="btn btn-link btn-xs" >
        <i class="fas fa-plus"></i> Agregar 
		</button>
	</form>
	<form action="{% url 'almacen:minus-1' pro.id %}" method="post" style="display: inline;">
		{% csrf_token %}
		<button type="submit" class="btn btn-link btn-xs" >
        <i class="fas fa-minus"></i> Quitar
		</button>
	</form>
	</td>
	{%endif%}

  </tr>
  {% endfor %}
     </tbody>
</table>
</div>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
        </main>
    </div>
</div>
{% endblock %}

templates/almacen/insumos.html
{% extends '../base.html' %}
{% block title %}Insumos | DIF Jalisco{% endblock %}
{% load static %}

{% block content %}
{% include "almacen/navbar.html" %}

{# Cambiar todo esto para que sea dinamico #}
<div class="container-fluid">
    <div class="row">
        <main role="main">
            <div class="flex-wrap flex-md-nowrap pt-3 pb-2 mb-3 border-bottom">
                {# include "almacen/alert.html" #}
                <div class="row">
                    <div class="col-md-1 col-auto"> <i class=" fas fa-capsules fa-3x"></i> </div>
                    <div class="col-md-1 col-auto">
                    <h1>Insumnos</h1>
                </div>
            </div>
            </div>
	{% include "almacen/sidebar.html" %}
    <div style="overflow-x:auto;">
<table class = "table table-hover">
  <tr>
    <th>Nombre</th>
    <th>Cantidad</th>
    <th>Almacen</th>
    <th>Prestados</th>
  </tr>
  {% for i in insumos %}
 <tr>
	 <td>{{i.name}}</td>
	 <td>{{i.cantidad}}</td>
	 <td>{{i.almacen}}</td>
	 <td>{{i.prestadas}}</td>

  </tr>
  {% endfor %}
</table>
<br>
<br>


<h2>Especiales</h2>

</table>
</div>

<div style="overflow-x:auto;">
<table class = "table table-hover">
  <tr class="active">
    <th>Nombre</th>
    <th>Cantidad</th>
    <th>Almacen</th>
    <th>Prestados</th>
  </tr>
  {% for e in espe %}
 <tr>
	 <td>{{e.name}}</td>
	 <td>{{e.cantidad}}</td>
	 <td>{{e.almacen}}</td>
	 <td>{{e.prestadas}}</td>
  </tr>
  {% endfor %}
</table>
</div>

        </main>
    </div>
</div>
{% endblock %}

templates/almacen/med.html
{% extends '../base.html' %}
{% block title %}Medicamentos | DIF Jalisco{% endblock %}
{% load static %}

{% block content %}
{% include "almacen/navbar.html" %}

{# Cambiar todo esto para que sea dinamico #}
<div class="container-fluid">
    <div class="row">
        <main role="main">
            <div class="flex-wrap flex-md-nowrap pt-3 pb-2 mb-3 border-bottom">
                <div class="row">
                    <div class="col-md-1 col-auto"> <i class="fas fa-box-open fa-3x"></i> </div>
                    <div class="col-md-1 col-auto">
                    <h1>Medicamentos</h1>
                </div>
            </div>
            </div>
	{% include "almacen/sidebar.html" %}

{% if medc != None %}
</table>
{% include "almacen/alert.html" %}
<div class="table-responsive">
    <div style="overflow-x:auto;">
<table class="table table-hover table-danger">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cantidad</th>
      <th>Caducidad</th>
    </tr>
  </thead>
  <tbody>
  {% for m in medc %}
 <tr>
	 <td>{{m.name}}</td>
	 <td>{{m.cantidad}}</td>
	 <td>{{m.fechaC}}</td>
  </tr>
  {% endfor %}
</tbody>
</table>
</div>
</div>
<br>
<br>
{%endif%}

<div class="table-responsive">
    <div style="overflow-x:auto;">
<table class = "table table-hover">
    <thead>
  <tr>
    <th>Nombre</th>
    <th>Cantidad</th>
    <th>Caducidad</th>
	{%if user.user_type != 5%}
    <th>Acciones</th>
	{%endif%}
  </tr>
  </thead>
   <tbody id="myTable">
  {% for med in medicamentos %}
 <tr>
	 <td>{{med.name}}</td>
	 <td>{{med.cantidad}}</td>
	 <td>{{med.fechaC}}</td>
	 {%if user.user_type != 5%}
	<td>                
	<form action="{% url 'almacen:addm-1' med.id %}" method="post" style="display: inline;">
		{% csrf_token %}
		<button type="submit" class="btn btn-link btn-xs" >
			<i class="fas fa-plus"></i> Agregar
		</button>
	</form>
	<form action="{% url 'almacen:minusm-1' med.id %}" method="post" style="display: inline;">
		{% csrf_token %}
		<button type="submit" class="btn btn-link btn-xs" >
			<i class="fas fa-minus"></i> Quitar
		</button>
	</form>
	</td>
	{%endif%}
  </tr>
  {% endfor %}
     </tbody>
</table>
</div>
</div>

<script>
$(document).ready(function(){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
        </main>
    </div>
</div>
{% endblock %}

templates/almacen/medicamentos_form.html
{% extends '../base.html' %}
{% block title %}Almacen | DIF Jalisco{% endblock %}
{% load static %}

{% block content %}
{% include "almacen/navbar.html" %}


	{% include "almacen/sidebar.html" %}
<div class="container-fluid">
    <div class="row">
        <main role="main">
            <div class="flex-wrap flex-md-nowrap pt-3 pb-2 mb-3 border-bottom">
                <div class="row">
                    <div class="col-md-1 col-auto"><i class="fas fa-plus fa-3x"></i></div>
                    <div class="col-md-1 col-auto">
                    <h1>Registro</h1>
                </div>
			
            </div>
            </div>

    	
<form method = "POST"  autocomplete="off">
{% csrf_token %}
{% for field in form %}
	<div 
		{% if field.id_for_label == 'id_refrigerado'%}
		    class="form-group form-check">
			<input id="{{ field.id_for_label }}"name="{{ field.html_name }}"
				type="checkbox" class="form-check-input"/> 
			<label class="form-check-label" for="id_refrigerado">Refrigerado</label> 
		{% else %}
			class="form-group"i>
			<input required 
				id="{{ field.id_for_label }}" maxlength="30" 
				name="{{ field.html_name }}"
				{% if field.id_for_label == 'id_fechaC' %}type="date" class="form-control" {% endif %}
				{% if field.id_for_label == 'id_cantidad' %}type="number" placeholder="Cantidad" class="form-control" {% endif %}
				{% if field.id_for_label == 'id_name' %}placeholder="Nombre" class="form-control" {% endif %}
				/> 	
		{% endif %}
	</div>
{% endfor %} 
<button class="btn btn-lg btn-info" type="submit">Guardar</button>
</form>

        </main>
    </div>
</div>

{% endblock %}

templates/almacen/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md fixed-top navbar-dark bg-info flex-md-nowrap p-0 shadow" >
    <button class="navbar-toggler" type="button" id="btn-navbar">
        <i class="fas fa-bars"></i>
    </button>
    <a class="navbar-brand col-md-2 col-sm-3 col-auto" href="{% url 'index'%}">
        <img src="{% static 'img/logo-lineal.png' %}" width="120" alt="DIF Jalisco">
    </a>
    <div class="input-group form-control-dark w-100">
        <div class="input-group-prepend">
            <div class="input-group-text"><i class="fas fa-search"></i></div>
        </div>
        <input type="text"id="myInput" class="form-control form-control-dark" placeholder="Buscar" autocomplete="off">
    </div>
</nav>